Version: 0.7.0
UserInfo:
  Username: keelus
  Password: '1234example'
SessionSettings:
  Lifespan: 365
  Unit: day
LedControl:
- true
- true
SystemStats:
- true
- true
- false
- false
- false
Logging: true
Security:
  UserInput: false
Units:
  TimeMode12: true
  TemperatureC: true
Design:
  Accent:
  - "#fdc830"
  - "#f37335"
  Fonts:
  - Title: Familjen Grotesk
    Source: https://fonts.googleapis.com/css2?family=Familjen+Grotesk:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap
  - Title: Fira Code
    Source: "#"
