Version: 0.7.4
UserInfo:
    Username: Keelus
    Password: $2a$10$s4Lxm2RBad42r53sX0BHHOwTOBye0ZNt49GljfIlPm8VcmuYMePDK
SessionSettings:
    Lifespan: 24
    Unit: hour
LedControl:
    - true
    - true
    - true
SystemStats:
    - true
    - true
    - true
    - true
    - true
Logging: true
Security:
    UserInput: false
Units:
    TimeMode12: true
    TemperatureC: true
Design:
    Accent:
        - '#fdc830'
        - '#f37335'
    Fonts:
        - Title: Familjen Grotesk
          Source: https://fonts.googleapis.com/css2?family=Familjen+Grotesk:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap
        - Title: Fira Code
          Source: '#'
