UserInfo:
    Username: 
    Password: 
ColorModeDark: false
SessionSettings:
    Lifespan: 24
    Unit: hour
LedControl:
    - true
    - true
    - true
SystemStats:
    - true
    - true
    - true
    - true
    - true
Logging: true
Security:
    UserInput: false
Units:
    TemperatureC: true